package com.dbdemo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dbdemo.bean.JoinTeacherToStudent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_TEACHER_TO_STUDENT".
*/
public class JoinTeacherToStudentDao extends AbstractDao<JoinTeacherToStudent, Long> {

    public static final String TABLENAME = "JOIN_TEACHER_TO_STUDENT";

    /**
     * Properties of entity JoinTeacherToStudent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property TId = new Property(1, long.class, "tId", false, "T_ID");
        public final static Property SId = new Property(2, long.class, "sId", false, "S_ID");
    }


    public JoinTeacherToStudentDao(DaoConfig config) {
        super(config);
    }
    
    public JoinTeacherToStudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_TEACHER_TO_STUDENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"T_ID\" INTEGER NOT NULL ," + // 1: tId
                "\"S_ID\" INTEGER NOT NULL );"); // 2: sId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_TEACHER_TO_STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinTeacherToStudent entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getTId());
        stmt.bindLong(3, entity.getSId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinTeacherToStudent entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getTId());
        stmt.bindLong(3, entity.getSId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public JoinTeacherToStudent readEntity(Cursor cursor, int offset) {
        JoinTeacherToStudent entity = new JoinTeacherToStudent( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // tId
            cursor.getLong(offset + 2) // sId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinTeacherToStudent entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTId(cursor.getLong(offset + 1));
        entity.setSId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinTeacherToStudent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinTeacherToStudent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinTeacherToStudent entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
