package com.dbdemo.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.dbdemo.bean.JoinTeacherToStudent;

import com.dbdemo.bean.Teacher;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEACHER".
*/
public class TeacherDao extends AbstractDao<Teacher, Long> {

    public static final String TABLENAME = "TEACHER";

    /**
     * Properties of entity Teacher.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property TId = new Property(1, long.class, "tId", false, "T_ID");
        public final static Property TName = new Property(2, String.class, "tName", false, "T_NAME");
        public final static Property TPhone = new Property(3, String.class, "tPhone", false, "T_PHONE");
    }

    private DaoSession daoSession;

    private Query<Teacher> student_TeachersQuery;

    public TeacherDao(DaoConfig config) {
        super(config);
    }
    
    public TeacherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEACHER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"T_ID\" INTEGER NOT NULL UNIQUE ," + // 1: tId
                "\"T_NAME\" TEXT," + // 2: tName
                "\"T_PHONE\" TEXT);"); // 3: tPhone
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEACHER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Teacher entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getTId());
 
        String tName = entity.getTName();
        if (tName != null) {
            stmt.bindString(3, tName);
        }
 
        String tPhone = entity.getTPhone();
        if (tPhone != null) {
            stmt.bindString(4, tPhone);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Teacher entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getTId());
 
        String tName = entity.getTName();
        if (tName != null) {
            stmt.bindString(3, tName);
        }
 
        String tPhone = entity.getTPhone();
        if (tPhone != null) {
            stmt.bindString(4, tPhone);
        }
    }

    @Override
    protected final void attachEntity(Teacher entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Teacher readEntity(Cursor cursor, int offset) {
        Teacher entity = new Teacher( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // tId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // tPhone
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Teacher entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTId(cursor.getLong(offset + 1));
        entity.setTName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTPhone(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Teacher entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Teacher entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Teacher entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "teachers" to-many relationship of Student. */
    public List<Teacher> _queryStudent_Teachers(long sId) {
        synchronized (this) {
            if (student_TeachersQuery == null) {
                QueryBuilder<Teacher> queryBuilder = queryBuilder();
                queryBuilder.join(JoinTeacherToStudent.class, JoinTeacherToStudentDao.Properties.TId)
                    .where(JoinTeacherToStudentDao.Properties.SId.eq(sId));
                student_TeachersQuery = queryBuilder.build();
            }
        }
        Query<Teacher> query = student_TeachersQuery.forCurrentThread();
        query.setParameter(0, sId);
        return query.list();
    }

}
